import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist, Montserrat } from "next/font/google";

export const metadata: Metadata = {
    title: "hooked/ai",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
    subsets: ["latin"],
    variable: "--font-geist-sans",
});

const monserrat = Montserrat({
    subsets: ["latin"],
    variable: "--font-montserrat",
    weight: ["400", "500", "600", "700"],
});

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" className={`${geist.variable} ${monserrat.variable}`}>
            <body>{children}</body>
        </html>
    );
}
